CREATE ROLE new_role;
GRANT CONNECT ON DATABASE busyblacklake TO new_role;
GRANT ALL PRIVILEGES ON DATABASE busyblacklake TO new_role;
GRANT ALL PRIVILEGES ON TABLESPACE oke11 TO new_role;
GRANT ALL PRIVILEGES ON TABLESPACE djb5 TO new_role;
GRANT ALL PRIVILEGES ON TABLESPACE ick81 TO new_role;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO new_role;
GRANT ALL PRIVILEGES ON TABLE table_oke11 TO new_role;
GRANT ALL PRIVILEGES ON TABLE table_djb5 TO new_role;
GRANT ALL PRIVILEGES ON TABLE table_ick81 TO new_role;

CREATE USER new_user;
GRANT new_role TO new_user;